/**
 * Förslagslista för artgrupper (species_group).
 *
 * OBS: Den här listan är ENBART en hjälp i formulär och import. Den är inte
 * sanningen för utbytestäckning — täckningen kontrolleras alltid mot verklig
 * produktdata och verkliga rader i `yields` (Inställningar →
 * "Kontrollera utbytestäckning").
 */
export const SPECIES_GROUP_SUGGESTIONS = [
  "torsk",
  "kolja",
  "sej",
  "bleka",
  "lubb",
  "långa",
  "kolfisk",
  "kummel",
  "kapkummel",
  "vitling",
  "havskatt",
  "kungsfisk",
  "stillahavskungsfisk",
  "lake",
  "knot",
  "fjärsing",
  "mullus",
  "silversida",
  "marulk",
  "red-snapper",
  "papegojfisk",
  "beryx",
  "taggmakrill",
  "gös",
  "abborre",
  "gädda",
  "sik",
  "rödspätta",
  "sjötunga",
  "bergtunga",
  "rödtunga",
  "piggvar",
  "slätvar",
  "sillflundra",
  "hälleflundra",
  "blåkveite",
  "lax",
  "stillahavslax",
  "regnbåge",
  "havsöring",
  "röding",
  "sill",
  "makrill",
  "sardin",
  "stenbit",
  "tonfisk",
  "blåfenad-tonfisk",
  "skipjack",
  "svärdfisk",
  "seriola",
  "dorade",
  "havsabborre",
  "madai",
  "bläckfisk",
  "calamari",
  "octopus",
  "havskräfta",
  "signalkräfta",
  "flodkräfta",
  "räka-nordhav",
  "vannameiräka",
  "tigerräka",
  "argentinsk-rödräka",
  "carabinero",
  "taskkrabba",
  "snökrabba",
  "kungskrabba",
  "softshell-crab",
  "hummer-europeisk",
  "hummer-amerikansk",
  "langust",
  "ostron-gigas",
  "ostron-platt",
  "blåmussla",
  "grönmussla",
  "hjärtmussla",
  "vongole",
  "knivmussla",
  "venusmussla",
  "mandelmussla",
  "kammussla",
  "drottningkammussla",
  "strandsnäcka",
  "valthornssnäcka",
  "abalone",
] as const;

/** Normaliserar en artgrupp till lagringsformat (gemener, trimmat). */
export function normalizeSpeciesGroup(value: unknown): string | null {
  const v = String(value ?? "").trim().toLowerCase();
  return v === "" ? null : v;
}
