project_id = "tzcvoqnrhjtrxlzhhdmu"

[functions.parse-foljesedel]
verify_jwt = false

[functions.archive-daily-reports]
verify_jwt = false

[functions.archive-daily-production-reports]
verify_jwt = false

[functions.seed-staff-users]
verify_jwt = false