// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-stores.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.117.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-stores.ts
var list_stores_default = defineTool({
  name: "list_stores",
  title: "Lista butiker och driftst\xE4llen",
  description: "Listar butiker och grossistenheter med stad, land, valuta och om enheten \xE4r aktiv.",
  inputSchema: {
    only_active: z.boolean().optional().describe("Visa bara aktiva enheter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("stores").select("id, name, city, country, currency, is_wholesale, active").order("name");
    if (only_active) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const stores = (data ?? []).map((s) => ({
      id: String(s.id),
      name: String(s.name ?? ""),
      city: s.city ? String(s.city) : null,
      country: s.country ? String(s.country) : null,
      currency: s.currency ? String(s.currency) : null,
      isWholesale: Boolean(s.is_wholesale),
      active: s.active === null ? null : Boolean(s.active)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(stores) }],
      structuredContent: { stores }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_products_default = defineTool2({
  name: "search_products",
  title: "S\xF6k varor",
  description: "S\xF6ker varor p\xE5 namn, artikelnummer eller streckkod och visar kategori, enhet och priser.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("S\xF6kord, artikelnummer eller streckkod."),
    limit: z2.number().int().min(1).max(50).optional().describe("Antal tr\xE4ffar, standard 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const safe = query.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("products").select(
      "id, sku, name, category, unit, cost_price, wholesale_price, retail_suggested, active"
    ).or(`name.ilike.%${safe}%,sku.ilike.%${safe}%,barcode.ilike.%${safe}%`).order("name").limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const products = (data ?? []).map((p) => ({
      id: String(p.id),
      sku: p.sku ? String(p.sku) : null,
      name: String(p.name ?? ""),
      category: p.category ? String(p.category) : null,
      unit: p.unit ? String(p.unit) : null,
      costPrice: p.cost_price === null ? null : Number(p.cost_price),
      wholesalePrice: p.wholesale_price === null ? null : Number(p.wholesale_price),
      retailSuggested: p.retail_suggested === null ? null : Number(p.retail_suggested),
      active: p.active === null ? null : Boolean(p.active)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/list-customer-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_customer_orders_default = defineTool3({
  name: "list_customer_orders",
  title: "Lista kundbest\xE4llningar",
  description: "Listar kundbest\xE4llningar med ordernummer, kund, \xF6nskat datum och tid, status och packstatus. Kan filtreras p\xE5 butik, datum och status.",
  inputSchema: {
    store_id: z3.string().uuid().optional().describe("Butikens id, fr\xE5n list_stores."),
    wanted_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("\xD6nskat leveransdatum, \xC5\xC5\xC5\xC5-MM-DD."),
    status: z3.string().trim().min(1).optional().describe("Orderstatus, exempelvis aktiv."),
    limit: z3.number().int().min(1).max(100).optional().describe("Antal rader, standard 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ store_id, wanted_date, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("customer_orders").select(
      "id, order_number, store_id, customer_name_snapshot, wanted_date, wanted_time, status, pack_status, total_incl_vat, currency, archived_at"
    ).order("wanted_date", { ascending: false }).order("wanted_time", { ascending: true }).limit(limit ?? 30);
    if (store_id) query = query.eq("store_id", store_id);
    if (wanted_date) query = query.eq("wanted_date", wanted_date);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = (data ?? []).map((o) => ({
      id: String(o.id),
      orderNumber: o.order_number ? String(o.order_number) : null,
      storeId: o.store_id ? String(o.store_id) : null,
      customerName: o.customer_name_snapshot ? String(o.customer_name_snapshot) : null,
      wantedDate: o.wanted_date ? String(o.wanted_date) : null,
      wantedTime: o.wanted_time ? String(o.wanted_time) : null,
      status: o.status ? String(o.status) : null,
      packStatus: o.pack_status ? String(o.pack_status) : null,
      totalInclVat: o.total_incl_vat === null ? null : Number(o.total_incl_vat),
      currency: o.currency ? String(o.currency) : null,
      archived: Boolean(o.archived_at)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(orders) }],
      structuredContent: { orders }
    };
  }
});

// src/lib/mcp/tools/get-lot.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_lot_default = defineTool4({
  name: "get_lot",
  title: "H\xE4mta parti f\xF6r sp\xE5rbarhet",
  description: "H\xE4mtar ett parti p\xE5 partinummer och visar art, f\xE5ngstomr\xE5de, redskap, f\xE5ngstdatum, b\xE4st f\xF6re, kvarvarande m\xE4ngd i kilo och status.",
  inputSchema: {
    lot_number: z4.string().trim().min(1).describe("Partinummer, exakt eller del av.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lot_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const safe = lot_number.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("lots").select(
      "id, lot_number, commercial_name, latin_name, catch_area, fishing_gear, production_method, catch_date_from, catch_date_to, best_before, quantity_kg, status, vessel_name, parent_lot_id"
    ).ilike("lot_number", `%${safe}%`).order("created_at", { ascending: false }).limit(10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: `Inget parti matchar ${lot_number}.` }], isError: true };
    }
    const lots = data.map((l) => ({
      id: String(l.id),
      lotNumber: String(l.lot_number ?? ""),
      commercialName: l.commercial_name ? String(l.commercial_name) : null,
      latinName: l.latin_name ? String(l.latin_name) : null,
      catchArea: l.catch_area ? String(l.catch_area) : null,
      fishingGear: l.fishing_gear ? String(l.fishing_gear) : null,
      productionMethod: l.production_method ? String(l.production_method) : null,
      catchDateFrom: l.catch_date_from ? String(l.catch_date_from) : null,
      catchDateTo: l.catch_date_to ? String(l.catch_date_to) : null,
      bestBefore: l.best_before ? String(l.best_before) : null,
      quantityKg: l.quantity_kg === null ? null : Number(Number(l.quantity_kg).toFixed(1)),
      status: l.status ? String(l.status) : null,
      vesselName: l.vessel_name ? String(l.vessel_name) : null,
      parentLotId: l.parent_lot_id ? String(l.parent_lot_id) : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(lots) }],
      structuredContent: { lots }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tzcvoqnrhjtrxlzhhdmu";
var mcp_default = defineMcp({
  name: "makrill-erp",
  title: "Makrill ERP",
  version: "0.1.0",
  instructions: "Verktyg f\xF6r Makrill ERP. L\xE4sande verktyg som k\xF6rs som den inloggade anv\xE4ndaren: list_stores f\xF6r butiker och driftst\xE4llen, search_products f\xF6r varor och priser, list_customer_orders f\xF6r kundbest\xE4llningar och get_lot f\xF6r partisp\xE5rbarhet.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_stores_default, search_products_default, list_customer_orders_default, get_lot_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
