// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-stores.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.117.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-stores.ts
var list_stores_default = defineTool({
  name: "list_stores",
  title: "Lista butiker och driftst\xE4llen",
  description: "Listar butiker och grossistenheter med stad, land, valuta och om enheten \xE4r aktiv.",
  inputSchema: {
    only_active: z.boolean().optional().describe("Visa bara aktiva enheter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("stores").select("id, name, city, country, currency, is_wholesale, active").order("name");
    if (only_active) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const stores = (data ?? []).map((s) => ({
      id: String(s.id),
      name: String(s.name ?? ""),
      city: s.city ? String(s.city) : null,
      country: s.country ? String(s.country) : null,
      currency: s.currency ? String(s.currency) : null,
      isWholesale: Boolean(s.is_wholesale),
      active: s.active === null ? null : Boolean(s.active)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(stores) }],
      structuredContent: { stores }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_products_default = defineTool2({
  name: "search_products",
  title: "S\xF6k varor",
  description: "S\xF6ker varor p\xE5 namn, artikelnummer eller streckkod och visar kategori, enhet och priser.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("S\xF6kord, artikelnummer eller streckkod."),
    limit: z2.number().int().min(1).max(50).optional().describe("Antal tr\xE4ffar, standard 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const safe = query.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("products").select(
      "id, sku, name, category, unit, cost_price, wholesale_price, retail_suggested, active"
    ).or(`name.ilike.%${safe}%,sku.ilike.%${safe}%,barcode.ilike.%${safe}%`).order("name").limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const products = (data ?? []).map((p) => ({
      id: String(p.id),
      sku: p.sku ? String(p.sku) : null,
      name: String(p.name ?? ""),
      category: p.category ? String(p.category) : null,
      unit: p.unit ? String(p.unit) : null,
      costPrice: p.cost_price === null ? null : Number(p.cost_price),
      wholesalePrice: p.wholesale_price === null ? null : Number(p.wholesale_price),
      retailSuggested: p.retail_suggested === null ? null : Number(p.retail_suggested),
      active: p.active === null ? null : Boolean(p.active)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/list-customer-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_customer_orders_default = defineTool3({
  name: "list_customer_orders",
  title: "Lista kundbest\xE4llningar",
  description: "Listar kundbest\xE4llningar med ordernummer, kund, \xF6nskat datum och tid, status och packstatus. Kan filtreras p\xE5 butik, datum och status.",
  inputSchema: {
    store_id: z3.string().uuid().optional().describe("Butikens id, fr\xE5n list_stores."),
    wanted_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("\xD6nskat leveransdatum, \xC5\xC5\xC5\xC5-MM-DD."),
    status: z3.string().trim().min(1).optional().describe("Orderstatus, exempelvis aktiv."),
    limit: z3.number().int().min(1).max(100).optional().describe("Antal rader, standard 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ store_id, wanted_date, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("customer_orders").select(
      "id, order_number, store_id, customer_name_snapshot, wanted_date, wanted_time, status, pack_status, total_incl_vat, currency, archived_at"
    ).order("wanted_date", { ascending: false }).order("wanted_time", { ascending: true }).limit(limit ?? 30);
    if (store_id) query = query.eq("store_id", store_id);
    if (wanted_date) query = query.eq("wanted_date", wanted_date);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = (data ?? []).map((o) => ({
      id: String(o.id),
      orderNumber: o.order_number ? String(o.order_number) : null,
      storeId: o.store_id ? String(o.store_id) : null,
      customerName: o.customer_name_snapshot ? String(o.customer_name_snapshot) : null,
      wantedDate: o.wanted_date ? String(o.wanted_date) : null,
      wantedTime: o.wanted_time ? String(o.wanted_time) : null,
      status: o.status ? String(o.status) : null,
      packStatus: o.pack_status ? String(o.pack_status) : null,
      totalInclVat: o.total_incl_vat === null ? null : Number(o.total_incl_vat),
      currency: o.currency ? String(o.currency) : null,
      archived: Boolean(o.archived_at)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(orders) }],
      structuredContent: { orders }
    };
  }
});

// src/lib/mcp/tools/get-lot.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_lot_default = defineTool4({
  name: "get_lot",
  title: "H\xE4mta parti f\xF6r sp\xE5rbarhet",
  description: "H\xE4mtar ett parti p\xE5 partinummer och visar art, f\xE5ngstomr\xE5de, redskap, f\xE5ngstdatum, b\xE4st f\xF6re, kvarvarande m\xE4ngd i kilo och status.",
  inputSchema: {
    lot_number: z4.string().trim().min(1).describe("Partinummer, exakt eller del av.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lot_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const safe = lot_number.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("lots").select(
      "id, lot_number, commercial_name, latin_name, catch_area, fishing_gear, production_method, catch_date_from, catch_date_to, best_before, quantity_kg, status, vessel_name, parent_lot_id"
    ).ilike("lot_number", `%${safe}%`).order("created_at", { ascending: false }).limit(10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: `Inget parti matchar ${lot_number}.` }], isError: true };
    }
    const lots = data.map((l) => ({
      id: String(l.id),
      lotNumber: String(l.lot_number ?? ""),
      commercialName: l.commercial_name ? String(l.commercial_name) : null,
      latinName: l.latin_name ? String(l.latin_name) : null,
      catchArea: l.catch_area ? String(l.catch_area) : null,
      fishingGear: l.fishing_gear ? String(l.fishing_gear) : null,
      productionMethod: l.production_method ? String(l.production_method) : null,
      catchDateFrom: l.catch_date_from ? String(l.catch_date_from) : null,
      catchDateTo: l.catch_date_to ? String(l.catch_date_to) : null,
      bestBefore: l.best_before ? String(l.best_before) : null,
      quantityKg: l.quantity_kg === null ? null : Number(Number(l.quantity_kg).toFixed(1)),
      status: l.status ? String(l.status) : null,
      vesselName: l.vessel_name ? String(l.vessel_name) : null,
      parentLotId: l.parent_lot_id ? String(l.parent_lot_id) : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(lots) }],
      structuredContent: { lots }
    };
  }
});

// src/lib/mcp/tools/ai-team.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var deny = { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
var fail = (m) => ({ content: [{ type: "text", text: m }], isError: true });
var ok = (key, v) => {
  const json = JSON.parse(JSON.stringify(v ?? null));
  return {
    content: [{ type: "text", text: JSON.stringify(json) }],
    structuredContent: { [key]: json }
  };
};
var uppgiftStatus = z5.enum(["\xF6ppen", "p\xE5g\xE5r", "v\xE4ntar p\xE5 vd", "klar"]);
var utkastStatus = z5.enum(["utkast", "redigerat", "godk\xE4nt", "skickat", "avslaget"]);
var read = { readOnlyHint: true, idempotentHint: true, openWorldHint: false };
var write = { readOnlyHint: false, destructiveHint: false, openWorldHint: false };
var listaAiUppgifter = defineTool5({
  name: "lista_ai_uppgifter",
  title: "Lista AI-uppgifter",
  description: "Listar AI-teamets uppgifter. Kan filtreras p\xE5 status och tilldelad.",
  inputSchema: {
    status: uppgiftStatus.optional(),
    tilldelad: z5.string().trim().min(1).optional(),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: read,
  handler: async ({ status, tilldelad, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return deny;
    let q = supabaseForUser(ctx).from("ai_uppgifter").select("*").order("skapad", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (tilldelad) q = q.eq("tilldelad", tilldelad);
    const { data, error } = await q;
    return error ? fail(error.message) : ok("uppgifter", data ?? []);
  }
});
var skapaAiUppgift = defineTool5({
  name: "skapa_ai_uppgift",
  title: "Skapa AI-uppgift",
  description: "Skapar en ny uppgift p\xE5 tavlan.",
  inputSchema: {
    uppgift: z5.string().trim().min(1),
    tilldelad: z5.string().trim().optional(),
    skapad_av: z5.string().trim().optional(),
    prioritet: z5.number().int().min(1).max(5).optional(),
    deadline: z5.string().optional().describe("ISO-tidpunkt."),
    underlag: z5.string().optional(),
    status: uppgiftStatus.optional()
  },
  annotations: write,
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return deny;
    const { data, error } = await supabaseForUser(ctx).from("ai_uppgifter").insert(input).select().single();
    return error ? fail(error.message) : ok("uppgift", data);
  }
});
var uppdateraAiUppgift = defineTool5({
  name: "uppdatera_ai_uppgift",
  title: "Uppdatera AI-uppgift",
  description: "Uppdaterar status och resultat p\xE5 en AI-uppgift.",
  inputSchema: {
    id: z5.number().int(),
    status: uppgiftStatus.optional(),
    resultat: z5.string().optional()
  },
  annotations: { ...write, idempotentHint: true },
  handler: async ({ id, status, resultat }, ctx) => {
    if (!ctx.isAuthenticated()) return deny;
    const patch = {};
    if (status) patch.status = status;
    if (resultat !== void 0) patch.resultat = resultat;
    const { data, error } = await supabaseForUser(ctx).from("ai_uppgifter").update(patch).eq("id", id).select().single();
    return error ? fail(error.message) : ok("uppgift", data);
  }
});
var listaAiUtkast = defineTool5({
  name: "lista_ai_utkast",
  title: "Lista AI-utkast",
  description: "Listar utkast som v\xE4ntar p\xE5 eller har passerat VD:s attest. Kan filtreras p\xE5 status och typ.",
  inputSchema: {
    status: utkastStatus.optional(),
    typ: z5.string().trim().min(1).optional(),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: read,
  handler: async ({ status, typ, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return deny;
    let q = supabaseForUser(ctx).from("ai_utkast").select("*").order("skapad", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (typ) q = q.eq("typ", typ);
    const { data, error } = await q;
    return error ? fail(error.message) : ok("utkast", data ?? []);
  }
});
var skapaAiUtkast = defineTool5({
  name: "skapa_ai_utkast",
  title: "Skapa AI-utkast",
  description: "Skapar ett nytt utkast f\xF6r VD:s attest.",
  inputSchema: {
    titel: z5.string().trim().min(1),
    typ: z5.string().optional(),
    mottagare: z5.string().optional(),
    kanal: z5.string().optional(),
    innehall: z5.string().optional().describe("Markdown."),
    bilaga_url: z5.string().url().optional(),
    skapad_av: z5.string().optional()
  },
  annotations: write,
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return deny;
    const { data, error } = await supabaseForUser(ctx).from("ai_utkast").insert(input).select().single();
    return error ? fail(error.message) : ok("utkast", data);
  }
});
var uppdateraAiUtkast = defineTool5({
  name: "uppdatera_ai_utkast",
  title: "Uppdatera AI-utkast",
  description: "Uppdaterar ett utkast: inneh\xE5ll, titel, mottagare, kanal, bilaga eller status.",
  inputSchema: {
    id: z5.number().int(),
    titel: z5.string().trim().min(1).optional(),
    mottagare: z5.string().optional(),
    kanal: z5.string().optional(),
    innehall: z5.string().optional(),
    bilaga_url: z5.string().url().optional(),
    status: utkastStatus.optional()
  },
  annotations: { ...write, idempotentHint: true },
  handler: async ({ id, ...rest }, ctx) => {
    if (!ctx.isAuthenticated()) return deny;
    const patch = Object.fromEntries(Object.entries(rest).filter(([, v]) => v !== void 0));
    if (patch.status === "skickat") patch.skickad = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabaseForUser(ctx).from("ai_utkast").update(patch).eq("id", id).select().single();
    return error ? fail(error.message) : ok("utkast", data);
  }
});

// src/lib/mcp/tools/ai-read.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z6 } from "npm:zod@^3.25.76";
var deny2 = { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
var fail2 = (m) => ({ content: [{ type: "text", text: m }], isError: true });
var ok2 = (key, v) => {
  const json = JSON.parse(JSON.stringify(v ?? null));
  return {
    content: [{ type: "text", text: JSON.stringify(json) }],
    structuredContent: { [key]: json }
  };
};
var read2 = { readOnlyHint: true, idempotentHint: true, openWorldHint: false };
var datum = z6.string().regex(/^\d{4}-\d{2}-\d{2}$/);
var common = {
  from_date: datum.optional().describe("Fr\xE5n och med datum, \xC5\xC5\xC5\xC5-MM-DD."),
  to_date: datum.optional().describe("Till och med datum, \xC5\xC5\xC5\xC5-MM-DD."),
  store_id: z6.string().uuid().optional().describe("Butikens id."),
  store_code: z6.string().trim().min(1).optional().describe("Butikskod, alternativ till store_id."),
  limit: z6.number().int().min(1).max(500).optional().describe("Antal rader, standard 100.")
};
function makeTool(s) {
  return defineTool6({
    name: s.name,
    title: s.title,
    description: s.description,
    inputSchema: { ...common, ...s.extra ?? {} },
    annotations: read2,
    handler: async (args, ctx) => {
      if (!ctx.isAuthenticated()) return deny2;
      const a = args;
      const db = supabaseForUser(ctx);
      let storeId = a.store_id;
      if (!storeId && a.store_code) {
        const { data: data2, error: error2 } = await db.from("stores").select("id").eq("store_code", a.store_code).maybeSingle();
        if (error2) return fail2(error2.message);
        if (!data2) return fail2(`Ingen butik med kod ${a.store_code}.`);
        storeId = data2.id;
      }
      if (storeId && !s.hasStore) return fail2("Tabellen saknar butikskoppling; filtrera utan butik.");
      let q = db.from(s.table).select(s.columns ?? "*").order(s.orderCol, { ascending: false }).limit(a.limit ?? 100);
      if (storeId) q = q.eq("store_id", storeId);
      if (s.dateCol && a.from_date) q = q.gte(s.dateCol, a.from_date);
      if (s.dateCol && a.to_date) q = q.lte(s.dateCol, s.dateIsTimestamp ? `${a.to_date}T23:59:59.999` : a.to_date);
      if (s.applyExtra) q = s.applyExtra(q, a);
      const { data, error } = await q;
      return error ? fail2(error.message) : ok2(s.key, data ?? []);
    }
  });
}
var note = " Filter: from_date, to_date, store_id eller store_code, limit. Nyast f\xF6rst.";
var listaDagsrapporter = makeTool({
  name: "lista_dagsrapporter",
  title: "Lista dagsrapporter",
  description: "Listar butikernas dagsrapporter med f\xF6rs\xE4ljning, kvitton, personal och svinn." + note,
  table: "daily_reports",
  key: "dagsrapporter",
  dateCol: "report_date",
  orderCol: "report_date",
  hasStore: true
});
var listaVeckorapporter = makeTool({
  name: "lista_veckorapporter",
  title: "Lista veckorapporter",
  description: "Listar veckorapporter per butik med f\xF6rs\xE4ljning, timmar och l\xE5sstatus. Datum filtreras p\xE5 veckostart." + note,
  table: "weekly_store_reports",
  key: "veckorapporter",
  dateCol: "week_start",
  orderCol: "week_start",
  hasStore: true
});
var listaKundordrarAi = makeTool({
  name: "lista_kundordrar_ai",
  title: "Lista kundordrar f\xF6r AI-teamet",
  description: "Listar kundordrar med alla orderf\xE4lt. Datum filtreras p\xE5 \xF6nskat datum. Kan \xE4ven filtreras p\xE5 pack_status och status." + note,
  table: "customer_orders",
  key: "kundordrar",
  dateCol: "wanted_date",
  orderCol: "wanted_date",
  hasStore: true,
  extra: {
    pack_status: z6.string().trim().min(1).optional().describe("Packstatus."),
    status: z6.string().trim().min(1).optional().describe("Orderstatus.")
  },
  applyExtra: (q, a) => {
    if (a.pack_status) q = q.eq("pack_status", a.pack_status);
    if (a.status) q = q.eq("status", a.status);
    return q;
  }
});
var listaAvvikelser = makeTool({
  name: "lista_avvikelser",
  title: "Lista avvikelser",
  description: "Listar avvikelser med \xE5tg\xE4rder, ansvarig, f\xF6rfallodatum och st\xE4ngning. Datum filtreras p\xE5 skapad." + note,
  table: "deviations",
  key: "avvikelser",
  dateCol: "created_at",
  dateIsTimestamp: true,
  orderCol: "created_at",
  hasStore: true
});
var listaForbattringsforslag = makeTool({
  name: "lista_forbattringsforslag",
  title: "Lista f\xF6rb\xE4ttringsf\xF6rslag",
  description: "Listar f\xF6rb\xE4ttringsf\xF6rslag med observation, f\xF6rslag, status och beslut. Datum filtreras p\xE5 skapad." + note,
  table: "improvement_suggestions",
  key: "forslag",
  dateCol: "created_at",
  dateIsTimestamp: true,
  orderCol: "created_at",
  hasStore: true,
  extra: { status: z6.string().trim().min(1).optional().describe("Status.") },
  applyExtra: (q, a) => a.status ? q.eq("status", a.status) : q
});
var listaChecklistdagar = makeTool({
  name: "lista_checklistdagar",
  title: "Lista checklistdagar",
  description: "Listar checklistdagar per butik med pass, ansvarig och status." + note,
  table: "checklist_days",
  key: "checklistdagar",
  dateCol: "checklist_date",
  orderCol: "checklist_date",
  hasStore: true
});
var listaFortnoxFakturajobb = makeTool({
  name: "lista_fortnox_fakturajobb",
  title: "Lista Fortnox-fakturajobb",
  description: "Listar fakturajobb mot Fortnox med status, dokumentnummer, belopp och fel. Saknar butikskoppling. Datum filtreras p\xE5 skapad." + note,
  table: "fortnox_invoice_jobs",
  key: "fakturajobb",
  dateCol: "created_at",
  dateIsTimestamp: true,
  orderCol: "created_at",
  hasStore: false,
  extra: { status: z6.string().trim().min(1).optional().describe("Jobbstatus.") },
  applyExtra: (q, a) => a.status ? q.eq("status", a.status) : q
});
var listaInkopsrapporter = makeTool({
  name: "lista_inkopsrapporter",
  title: "Lista ink\xF6psrapporter",
  description: "Listar ink\xF6psdokument som fakturor och f\xF6ljesedlar med leverant\xF6r, belopp och status. Saknar butikskoppling. Datum filtreras p\xE5 dokumentdatum." + note,
  table: "purchase_reports",
  key: "inkopsrapporter",
  dateCol: "document_date",
  orderCol: "created_at",
  hasStore: false,
  extra: { document_type: z6.string().trim().min(1).optional().describe("Dokumenttyp.") },
  applyExtra: (q, a) => a.document_type ? q.eq("document_type", a.document_type) : q
});
var listaOppettider = makeTool({
  name: "lista_oppettider",
  title: "Lista \xF6ppettider",
  description: "Listar butikernas \xF6ppettider per veckodag (1 m\xE5ndag till 7 s\xF6ndag). Datumfilter ignoreras eftersom tabellen saknar datum." + note,
  table: "store_opening_hours",
  key: "oppettider",
  orderCol: "updated_at",
  hasStore: true
});
var listaButiksvader = makeTool({
  name: "lista_butiksvader",
  title: "Lista butiksv\xE4der",
  description: "Listar dagligt v\xE4der per butik med temperatur, nederb\xF6rd och vind." + note,
  table: "store_weather_daily",
  key: "vader",
  dateCol: "weather_date",
  orderCol: "weather_date",
  hasStore: true
});

// src/lib/mcp/index.ts
var projectRef = "tzcvoqnrhjtrxlzhhdmu";
var mcp_default = defineMcp({
  name: "makrill-erp",
  title: "Makrill ERP",
  version: "0.1.0",
  instructions: "Verktyg f\xF6r Makrill ERP. L\xE4sande verktyg som k\xF6rs som den inloggade anv\xE4ndaren: list_stores f\xF6r butiker och driftst\xE4llen, search_products f\xF6r varor och priser, list_customer_orders f\xF6r kundbest\xE4llningar och get_lot f\xF6r partisp\xE5rbarhet. AI-teamet: lista_ai_uppgifter, skapa_ai_uppgift, uppdatera_ai_uppgift, lista_ai_utkast, skapa_ai_utkast och uppdatera_ai_utkast (kr\xE4ver administrat\xF6rsroll). L\xE4sverktyg f\xF6r AI-teamet: lista_dagsrapporter, lista_veckorapporter, lista_kundordrar_ai, lista_avvikelser, lista_forbattringsforslag, lista_checklistdagar, lista_fortnox_fakturajobb, lista_inkopsrapporter, lista_oppettider och lista_butiksvader.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_stores_default,
    search_products_default,
    list_customer_orders_default,
    get_lot_default,
    listaAiUppgifter,
    skapaAiUppgift,
    uppdateraAiUppgift,
    listaAiUtkast,
    skapaAiUtkast,
    uppdateraAiUtkast,
    listaDagsrapporter,
    listaVeckorapporter,
    listaKundordrarAi,
    listaAvvikelser,
    listaForbattringsforslag,
    listaChecklistdagar,
    listaFortnoxFakturajobb,
    listaInkopsrapporter,
    listaOppettider,
    listaButiksvader
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
