CREATE INDEX IF NOT EXISTS idx_notifications_portal_unread ON public.notifications (portal, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_portal_store_unread ON public.notifications (portal, store_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications (user_id, portal, is_read);
CREATE INDEX IF NOT EXISTS idx_shop_orders_created_at ON public.shop_orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shop_orders_status_created_at ON public.shop_orders (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shop_order_lines_order ON public.shop_order_lines (shop_order_id);
CREATE INDEX IF NOT EXISTS idx_shop_order_lines_product ON public.shop_order_lines (product_id);
CREATE INDEX IF NOT EXISTS idx_products_active_name ON public.products (active, name);
CREATE INDEX IF NOT EXISTS idx_stock_movements_lot_created ON public.stock_movements (lot_id, created_at DESC) WHERE lot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_stock_movements_created_at ON public.stock_movements (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movements_product ON public.stock_movements (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_location ON public.stock_movements (location_id);
CREATE INDEX IF NOT EXISTS idx_entity_images_type_cover ON public.entity_images (entity_type, is_cover DESC, sort_order);
CREATE INDEX IF NOT EXISTS idx_entity_images_entity ON public.entity_images (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_psl_quantity ON public.product_stock_locations (quantity DESC) WHERE quantity > 0;
CREATE INDEX IF NOT EXISTS idx_psl_product ON public.product_stock_locations (product_id);
CREATE INDEX IF NOT EXISTS idx_psl_location ON public.product_stock_locations (location_id);
CREATE INDEX IF NOT EXISTS idx_customer_orders_active_wanted ON public.customer_orders (wanted_date, wanted_time) WHERE archived_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customer_order_lines_order ON public.customer_order_lines (customer_order_id);
ANALYZE public.notifications;
ANALYZE public.shop_orders;
ANALYZE public.shop_order_lines;
ANALYZE public.products;
ANALYZE public.stock_movements;
ANALYZE public.entity_images;
ANALYZE public.product_stock_locations;
ANALYZE public.customer_orders;
ANALYZE public.customer_order_lines;