REVOKE EXECUTE ON FUNCTION public.absence_requests_sync_days() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.block_self_attestation() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_edit_daily_report_admin() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_manage_schedule(uuid, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_see_employee(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.clock_pending_approve(uuid, uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.clock_station_revoke(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.employee_is_self(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_daily_report_edit() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_shift_change() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.my_employee_ids() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.my_employee_store_ids() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.period_is_locked(uuid, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.preliminar_manadskostnad(uuid, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refresh_weekly_corrected_flag(uuid, date) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.time_entries_sync_staff_shift() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trg_mark_week_corrected() FROM anon, PUBLIC;

GRANT EXECUTE ON FUNCTION public.can_manage_schedule(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_see_employee(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.clock_pending_approve(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.clock_station_revoke(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.employee_is_self(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_employee_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_employee_store_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.period_is_locked(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.preliminar_manadskostnad(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_weekly_corrected_flag(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_edit_daily_report_admin() TO authenticated;